### ISSUE TITLE
Docker y AWS

### ISSUE THREAD

**Issue by dapivei** [C1587S/MNO_numericalOptimization#3]
*Tasks:*
- [x] Definición de paqueterías.

- [x]  Documentación

- [x] Instancia EC2

- [x] Imagen de Docker

**Comment by C1587S** [comment]
Hola!
Vamos 1/2 con este issue.
- Se incluyó ambiente de `docker` y se actualizaron paqueterías asociadas (requirements.txt), documentación.
- También se incluyó un botón de binder asociado a este repo.
__Aún falta crear instancia `EC2`__

**Comment by dapivei** [comment]
**Update:**

Se levantó una instancia EC2 dentro de una VPC que vive dentro de la VPC 'proyecto-final' con las características necesarias para correr el proyecto. Estamos usando una instancia con ´ubuntu server 18.04´ con ´1 GB´ de memoria RAM y 4 procesadores (por definir).  Más información, revisar [aquí](https://github.com/C1587S/MNO_numericalOptimization/tree/master/aws).
